version: 1.0
headless: true # replace with false if you want to show the browser
profile_path: "" # Insert path to your browser profile
week_offset: 16
section_id: '' # Replace with ID of option in the HTML
channels:
    1: "" # Webhook url to channel 1
    2: "" # Webhook url to channel 2
    3: "" # Webhook url to channel 3
    4: "" # Webhook url to channel 4
    5: "" # Webhook url to channel 5
message_ids:
    1: '' # Replace with id of message of bot in channel 1 (so the bot modifies it) or leave empty (bot will automatically insert the message ID here)
    2: '' # Replace with id of message of bot in channel 2 (so the bot modifies it) or leave empty (bot will automatically insert the message ID here)
    3: '' # Replace with id of message of bot in channel 3 (so the bot modifies it) or leave empty (bot will automatically insert the message ID here)
    4: '' # Replace with id of message of bot in channel 4 (so the bot modifies it) or leave empty (bot will automatically insert the message ID here)
    5: '' # Replace with id of message of bot in channel 5 (so the bot modifies it) or leave empty (bot will automatically insert the message ID here)
roles:
    1: '' # Replace with the ID of the role for the channel 1 (to ping)
    2: '' # Replace with the ID of the role for the channel 2 (to ping)
    3: '' # Replace with the ID of the role for the channel 3 (to ping)
    4: '' # Replace with the ID of the role for the channel 4 (to ping)
    5: '' # Replace with the ID of the role for the channel 5 (to ping)
